### ISSUE TITLE
Initialize Project Environment

### ISSUE THREAD

**Issue by crow50** [crow50/ernest-portfolio#12]
# **Convert Portfolio Page to Dynamic Content**

### **Summary:**
Get the project environment set up and ready for development

### **Tasks:**
- [x] Initialize the project
- [x] Create and activate a virtual environment
- [x] Push the initial setup to GitHub
