### ISSUE TITLE
Create Home Page Route and View

### ISSUE THREAD

**Issue by crow50** [crow50/ernest-portfolio#13]
# **Create Home Page Route and View**

### **Summary:**
Serve the home page dynamically using Flask

### **Tasks:**
- [x] Create a route/view for the home page
- [x] Move `index.html` to the templates folder
- [x] Ensure the page loads correctly

**Comment by crow50** [comment]
Need to maintain compatibility with current current pages
