### ISSUE TITLE
Implement Dynamic Portfolio Page

### ISSUE THREAD

**Issue by crow50** [crow50/ernest-portfolio#15]
# **Implement Dynamic Portfolio Page**

### **Summary:**
Display projects dynamically on the portfolio page

### **Tasks:**
- [x] Homepage: Summary of professional background
- [x] About Me
- [x] Projects
- [x] Create a data structure for projects
- [x] Update the portfolio template to loop over this data
- [x] Contact Page
