### ISSUE TITLE
Test and Polish

### ISSUE THREAD

**Issue by crow50** [crow50/ernest-portfolio#17]
# **Test and Polish**

### **Summary:**
Thoroughly test the site and fix any issues

### **Tasks:**
- [ ] Test each page for functionality
- [ ] Debug any problems that arise
- [ ] Polish up any rough edges

**Comment by crow50** [comment]
Tested and corrected for issues found. More polish to come.
