### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by crow50** [crow50/ernest-portfolio#18]
# **Document Setup and Progress**

### **Summary:**
Document the setup process and progress

### **Tasks:**
- [ ] Update `README.md` with setup instructions
- [x] Maintain `CHANGELOG.md` 
- [x] Update templates
- [ ] Create CoC
- [ ] Create Contributing instructions
